server:
  port: 8083

spring:
  application:
    name: api-rate-limiter

logging:
  level:
    root: INFO
    com.example.backend: DEBUG
    com.example.backend.config: TRACE
    com.example.backend.filter: TRACE